name: Sourish Ghosh
description: Dare Mighty Things
meta_description: "I am a Ph.D. student in the Robotics Institute, CMU associated with the Air Lab. Prior to this, I received my Bachelor’s and Master’s degree in Mathematics and Computing from IIT Kharagpur."
meta_tags: "sourish, ghosh, iit, kharagpur, space, robotics, computer vision, cmu, carnegie mellon university"

aboutPage: true

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 20
baseurl:
domain_name: 'http://sourishghosh.com'
google_analytics: 'UA-82908038-1'
disqus: true
disqus_shortname: 'sourishghosh'

#social-icons
facebook: lordghosh
twitter: sourish_gh
instagram: darthsourish
linkedin: sourishg
github: sourishg
email: ragnarok0211@gmail.com
scholar: 45-8VtAAAAAJ

# Details for the RSS feed generator
url:            'http://sourishghosh.com'
author:         'Sourish Ghosh'
authorTwitter:  'sourish_gh'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
