name: Sourish Ghosh
description: Dare Mighty Things
meta_description: "I am an undergraduate student at IIT Kharagpur, majoring in Mathematics and Computing. My research interests mainly lie in perception and planning for autonomous mobile robots."
meta_tags: "sourish, ghosh, iit, kharagpur, space, robotics, computer vision"

aboutPage: true

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

gems: [jekyll-paginate]
paginate: 20
baseurl: http://sourishghosh.com/
domain_name: 'http://sourishghosh.com'
google_analytics: 'UA-82908038-1'
disqus: true
disqus_shortname: 'sourishghosh'

#social-icons
facebook: lordghosh
twitter: sourish_gh
instagram: darthsourish
linkedin: sourishg
github: sourishg
email: sourishg@iitkgp.ac.in

# Details for the RSS feed generator
url:            'http://sourishghosh.com'
author:         'Sourish Ghosh'
authorTwitter:  'sourish_gh'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
