version: "3"
services:
    jekyll:
        build: .
        command: bundle exec jekyll serve --watch --incremental --trace
        ports:
            - 4000:4000
        volumes:
            - ./:/srv/jekyll